version: "3.9"

services:
  server:
    restart: always
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    image: myapp.latest
    links:
      - postgres:postgres
    ports:
      - 8080:8080
    depends_on:
      - postgres
    command: ["/app/wait-for-it.sh", "postgres:5432", "--", "/app/server"]

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/data/postgres

  # nginx:
  #   image: nginx:1.17
  #   links:
  #     - server:server
  #   depends_on:
  #     - server
  #   volumes:
  #     - ../configs/nginx:/etc/nginx/conf.d
  #   ports:
  #     - 8082:80
